- name: Generate fast, huge output with debug
  hosts: localhost
  gather_facts: no

  vars:
    total_messages: 5000

  tasks:

    - name: Print fast debug messages in loop
      debug:
        msg: "Line number {{ item }}"
      loop: "{{ range(1, total_messages + 1) | list }}"